### ISSUE TITLE
Describe how streams and Exasol fit together

### ISSUE THREAD

**Issue by jakobbraun** [exasol/kinesis-connector-extension#17]
I don't get how a kindesis stream can be integrated into Exasol, and what the use-cases are.
Some explanation on that topic in the readme would be great.

**Comment by AnastasiiaSergienko** [comment]
@jakobbraun 
Would it be enough if I link this article in the docs or do you mean some other explanation? 
https://community.exasol.com/t5/tech-blog/how-to-import-data-from-aws-kinesis-data-streams-with-our/ba-p/1704
